<?xml version="1.0" ?>

<!DOCTYPE mappings [
<!ELEMENT element (#PCDATA)>
<!ATTLIST element
    name CDATA #REQUIRED
    column CDATA #REQUIRED
    type CDATA #REQUIRED>
<!ELEMENT mapping (field|reference)*>
<!ATTLIST mapping
    class CDATA #REQUIRED
    lastModified CDATA #IMPLIED
    name CDATA #REQUIRED
    primaryKey CDATA #REQUIRED
    table CDATA #REQUIRED>
<!ELEMENT association (element)*>
<!ATTLIST association
    table CDATA #REQUIRED>
<!ELEMENT field (#PCDATA)>
<!ATTLIST field
    name CDATA #REQUIRED
    column CDATA #REQUIRED>
<!ELEMENT mappings (mapping|association)*>
<!ELEMENT reference (#PCDATA)>
<!ATTLIST reference
    name CDATA #REQUIRED
    column CDATA #REQUIRED
    type CDATA #IMPLIED>
]>

<mappings>
	<mapping name="Sequence" class="com.kiwisoft.utils.db.Sequence" table="sequences" primaryKey="name">
		<field name="name" column="name"/>
		<field name="value" column="value"/>
	</mapping>
	<mapping name="Show" class="com.kiwisoft.media.show.Show" table="shows" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="userKey" column="userkey"/>
		<field name="name" column="name"/>
		<field name="originalName" column="name_original"/>
		<field name="internet" column="internet"/>
		<field name="defaultEpisodeLength" column="episode_length"/>
		<field name="webDatesFile" column="webdatesfile"/>
		<field name="lastModified" column="lastmodified"/>
		<field name="logoMini" column="logo_mini"/> 
		<reference name="language" column="language_id" type="Language"/>
		<reference name="type" column="type_id"/>
		<reference name="defaultInfo" column="defaultinfo_id" type="ShowInfo"/>
	</mapping>
	<mapping name="ShowInfo" class="com.kiwisoft.media.show.ShowInfo" table="showinfos" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="name" column="name"/>
		<field name="path" column="path"/>
		<field name="lastModified" column="lastmodified"/>
		<reference name="show" column="show_id" type="Show"/>
		<reference name="language" column="language_id" type="Language"/>
	</mapping>
	<mapping name="Name" class="com.kiwisoft.media.Name" table="names" primaryKey="id">
		<field name="id" column="id"/>
		<field name="refId" column="ref_id"/>
		<field name="type" column="type"/>
		<field name="name" column="name"/>
		<reference name="language" column="language_id" type="Language"/>
	</mapping>
	<mapping name="Airdate" class="com.kiwisoft.media.Airdate" table="airdates" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="event" column="event"/>
		<reference name="show" column="show_id" type="Show"/>
		<reference name="episode" column="episode_id" type="Episode"/>
		<reference name="language" column="language_id" type="Language"/>
		<reference name="movie" column="movie_id" type="Movie"/>
		<field name="reminder" column="reminder"/>
		<field name="date" column="viewdate"/>
		<reference name="channel" column="channel_id" type="Channel"/>
		<field name="channelName" column="channel"/>
		<field name="lastModified" column="lastmodified"/>
		<reference name="dataSource" column="source_id"/>
	</mapping>
	<mapping name="Language" class="com.kiwisoft.media.Language" table="languages" primaryKey="id">
		<field name="id" column="id"/>
		<field name="symbol" column="symbol"/>
		<field name="name" column="name"/>
	</mapping>
	<mapping name="Channel" class="com.kiwisoft.media.Channel" table="channels" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="name" column="name"/>
		<field name="logo" column="logo"/>
		<reference name="language" column="language_id" type="Language"/>
		<field name="receivable" column="receivable"/>
		<field name="lastModified" column="lastmodified"/>
	</mapping>
	<mapping name="Recording" class="com.kiwisoft.media.video.Recording" table="recordings" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="longPlay" column="longplay"/>
		<field name="length" column="length"/>
		<field name="event" column="event"/>
		<reference name="show" column="show_id" type="Show"/>
		<reference name="episode" column="episode_id" type="Episode"/>
		<reference name="language" column="language_id" type="Language"/>
		<reference name="video" column="video_id" type="Video"/>
		<reference name="movie" column="movie_id" type="Movie"/>
		<field name="sequence" column="sequence"/>
		<field name="lastModified" column="lastmodified"/>
	</mapping>
	<mapping name="Video" class="com.kiwisoft.media.video.Video" table="videos" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="userKey" column="userkey"/>
		<field name="name" column="name"/>
		<field name="length" column="length"/>
		<field name="remainingLength" column="remaininglength"/>
		<reference name="type" column="type_id"/>
		<field name="lastModified" column="lastmodified"/>
	</mapping>
	<mapping name="Episode" class="com.kiwisoft.media.show.Episode" table="episodes" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="userKey" column="userkey"/>
		<field name="sequence" column="sequence"/>
		<field name="name" column="name"/>
		<field name="originalName" column="name_original"/>
		<field name="seen" column="seen"/>
		<field name="good" column="good"/>
		<field name="record" column="record"/>
		<field name="javaScript" column="javascript"/>
		<field name="webScriptFile" column="webscriptfile"/>
		<field name="lastModified" column="lastmodified"/>
		<reference name="show" column="show_id" type="Show"/>
		<reference name="defaultInfo" column="defaultinfo_id" type="EpisodeInfo"/>
	</mapping>
	<mapping name="EpisodeInfo" class="com.kiwisoft.media.show.EpisodeInfo" table="episodeinfos" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="name" column="name"/>
		<field name="path" column="path"/>
		<field name="lastModified" column="lastmodified"/>
		<reference name="episode" column="episode_id" type="Episode"/>
		<reference name="language" column="language_id" type="Language"/>
	</mapping>
	<mapping name="Movie" class="com.kiwisoft.media.movie.Movie" table="movies" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="name" column="name"/>
		<field name="originalName" column="name_original"/>
		<field name="seen" column="seen"/>
		<field name="good" column="good"/>
		<field name="record" column="record"/>
		<field name="javaScript" column="javascript"/>
		<field name="webScriptFile" column="webscriptfile"/>
		<field name="lastModified" column="lastmodified"/>
		<reference name="show" column="show_id" type="Show"/>
		<reference name="defaultInfo" column="defaultinfo_id" type="MovieInfo"/>
		<reference name="type" column="type_id"/>
	</mapping>
	<mapping name="MovieInfo" class="com.kiwisoft.media.movie.MovieInfo" table="movieinfos" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="name" column="name"/>
		<field name="path" column="path"/>
		<field name="lastModified" column="lastmodified"/>
		<reference name="movie" column="movie_id" type="Movie"/>
		<reference name="language" column="language_id" type="Language"/>
	</mapping>
	<mapping name="SearchPattern" class="com.kiwisoft.media.SearchPattern" table="searchpatterns" primaryKey="id">
		<field name="id" column="id"/>
		<field name="type" column="type"/>
		<reference name="show" column="show_id" type="Show"/>
		<reference name="movie" column="movie_id" type="Movie"/>
		<reference name="actor" column="actor_id" type="Person"/> 
		<field name="pattern" column="pattern"/>
	</mapping>
	<mapping name="Person" class="com.kiwisoft.media.Person" table="persons" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="firstName" column="firstname"/>
		<field name="middleName" column="middlename"/>
		<field name="surname" column="surname"/>
		<reference name="sex" column="sex_id"/>
		<field name="actor" column="actor"/>
		<field name="lastModified" column="lastmodified"/>
	</mapping>
	<mapping name="Character" class="com.kiwisoft.media.ShowCharacter" table="characters" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="name" column="name"/>
		<field name="nickName" column="nickname"/>
		<reference name="sex" column="sex_id"/>
		<field name="lastModified" column="lastmodified"/>
	</mapping>
	<mapping name="Cast" class="com.kiwisoft.media.Cast" table="cast" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="type" column="type"/>
		<field name="voice" column="voice"/>
		<field name="lastModified" column="lastmodified"/>
		<field name="imageSmall" column="image_small"/>
		<field name="imageLarge" column="image_large"/>
		<field name="description" column="description"/>  
		<reference name="actor" column="actor_id" type="Person"/>
		<reference name="character" column="character_id" type="Character"/>
		<reference name="show" column="show_id" type="Show"/>
		<reference name="episode" column="episode_id" type="Episode"/>
	</mapping>
	<mapping name="ContactMedium" class="com.kiwisoft.media.ContactMedium" table="contactmedia" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="type" column="type"/>
		<field name="value" column="value"/>
		<reference name="author" column="author_id" type="FanFicAuthor"/>
		<field name="lastModified" column="lastmodified"/>
	</mapping>
	<mapping name="FanFicAuthor" class="com.kiwisoft.media.fanfic.Author" table="fanficauthors" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="name" column="name"/>
		<field name="path" column="path"/>
		<field name="lastModified" column="lastmodified"/>
	</mapping>
	<mapping name="FanDom" class="com.kiwisoft.media.fanfic.FanDom" table="fandoms" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="name" column="name"/>
		<field name="lastModified" column="lastmodified"/>
		<reference name="show" column="show_id" type="Show"/>
		<reference name="movie" column="movie_id" type="Movie"/>
	</mapping>
	<mapping name="Pairing" class="com.kiwisoft.media.fanfic.Pairing" table="pairings" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="name" column="name"/>
		<field name="lastModified" column="lastmodified"/>
	</mapping>
	<mapping name="FanFic" class="com.kiwisoft.media.fanfic.FanFic" table="fanfics" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="title" column="title"/>
		<field name="rating" column="rating"/>
		<field name="description" column="description"/>
		<field name="finished" column="finished"/>
		<field name="spoiler" column="spoiler"/>
		<field name="url" column="url"/>
		<field name="lastModified" column="lastmodified"/>
		<reference name="sequel" column="sequel_id" type="FanFic"/>
		<reference name="prequel" column="prequel_id" type="FanFic"/>
	</mapping>
	<mapping name="FanFicPart" class="com.kiwisoft.media.fanfic.FanFicPart" table="fanfic_parts" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="sequence" column="sequence"/>
		<field name="lastModified" column="lastmodified"/>
		<field name="source" column="source"/>
		<reference name="fanFic" column="fanfic_id" type="FanFic"/>
	</mapping>
	<mapping name="Season" class="com.kiwisoft.media.show.Season" table="seasons" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="lastModified" column="lastmodified"/>
		<field name="number" column="number"/>
		<field name="name" column="name"/>
		<reference name="show" column="show_id" type="Show"/>
		<reference name="firstEpisode" column="firstepisode_id" type="Episode"/>
		<reference name="lastEpisode" column="lastepisode_id" type="Episode"/>
		<field name="startYear" column="startyear"/>
		<field name="endYear" column="endyear"/>
	</mapping>
	<mapping name="Link" class="com.kiwisoft.media.Link" table="links" primaryKey="id" lastModified="lastmodified">
		<field name="id" column="id"/>
		<field name="lastModified" column="lastmodified"/>
		<field name="name" column="name"/>
		<field name="url" column="url"/>
		<reference name="show" column="show_id" type="Show"/>
		<reference name="fanDom" column="fandom_id" type="FanDom"/>
		<reference name="language" column="language_id" type="Language"/>
	</mapping>

	<association table="map_fanfic_pairing">
		<element type="FanFic" name="pairings" column="fanfic_id"/>
		<element type="Pairing" name="fanfics" column="pairing_id"/>
	</association>
	<association table="map_fanfic_author">
		<element type="FanFic" name="authors" column="fanfic_id"/>
		<element type="FanFicAuthor" name="fanfics" column="author_id"/>
	</association>
	<association table="map_fanfic_fandom">
		<element type="FanFic" name="fandoms" column="fanfic_id"/>
		<element type="FanDom" name="fanfics" column="fandom_id"/>
	</association>
	<association table="map_pairing">
		<element type="Pairing" name="characters" column="pairing_id"/>
		<element type="Character" name="pairings" column="character_id"/>
	</association>
</mappings>